//Redux
const FETCHED_LESSOR = "FETCHED_LESSOR";
const FETCHED_LIST_LESSOR = "FETCHED_LIST_LESSOR";
const FETCHED_APARTMENT = "FETCHED_APARTMENT";
const SET_CHECK_IN_DATE = "GET_CHECK_IN_DATE";
const SET_CHECK_OUT_DATE = "GET_CHECK_OUT_DATE";
const SET_REQUIREMENT = "SET_REQUIREMENT";
const FETCHED_USER = "FETCHED_USER";
const SET_LESSOR_EDIT_ID = "SET_LESSOR_EDIT_ID";
const SET_EDIT_LESSOR_MODAL = "SET_EDIT_LESSOR_MODAL";
const TYPE_VOUCHER = "apart";
const SERVICE_CODE = "APART";
const APP_ID = "vy03";
// Others

export {
	FETCHED_LESSOR,
	FETCHED_LIST_LESSOR,
	FETCHED_APARTMENT,
	SET_CHECK_IN_DATE,
	SET_CHECK_OUT_DATE,
	SET_REQUIREMENT,
	FETCHED_USER,
	SET_LESSOR_EDIT_ID,
	SET_EDIT_LESSOR_MODAL,
	APP_ID,
	TYPE_VOUCHER,
	SERVICE_CODE,
};
